### ISSUE TITLE
Update the version of fr24feed?

### ISSUE THREAD

**Issue by SoNic1967** [abcd567a/fr24feed-debian-ubuntu-amd64-i386#1]
The latest AMD64 version supposedly is 1.0.34-0

**Comment by abcd567a** [comment]
Thank for pointing out. I will soon update the scripts and Readme. Meanwhile to upgrade an existing install of older version:

```
wget https://repo-feed.flightradar24.com/linux_x86_64_binaries/fr24feed_1.0.34-0_amd64.deb  
```

```
sudo dpkg -i fr24feed_1.0.34-0_amd64.deb  

```

For new installs:
After above two commands, signup:
`sudo fr24feed --signup  `

**Comment by IouSASTU** [comment]
Recently got the email that I needed to update as I was on a soon to be unsupported version of fr24feed. Just used your instructions to upgrade to the current version. Thank you for your work @abcd567a.
